#Define funcoes para verificar a logica de execucao de uma aplicacao leitor/escritor

class LE:
	def __init__(self):
		self.escritores = 0
		self.leitores = 0
		self.esperaEscritores = 0 # define o número de threads na espera da escrita

	def leitorBloqueado(self,id):
		'''Recebe o id do leitor. Verifica se a decisao de bloqueio esta correta.'''
		if(self.escritores==0) and (self.esperaEscritores == 0):
			print("ERRO: leitor " + str(id) + " bloqueado quando nao ha escritores!")

	def escritorBloqueado(self,id):
		'''Recebe o id do escritor. Verifica se a decisao de bloqueio esta correta.'''
		if(self.escritores==0) and (self.leitores==0):
			print("ERRO: escritor " + str(id) + " bloqueado quando nao ha escritores nem leitores!")
		self.esperaEscritores += 1 # Quando o escritor é bloqueado ele fica na espera

	def leitorLendo(self,id):
		'''Recebe o id do leitor, verifica se pode ler e registra que esta lendo.'''
		if(self.escritores>0):
			print("ERRO: leitor " + str(id) + " esta lendo quando ha escritor escrevendo!")
		self.leitores+=1

	def escritorEscrevendo(self,id):
		'''Recebe o id do escritor, verifica se pode escrever e registra que esta escrevendo'''
		if(self.escritores>0 or self.leitores>0):
			print("ERRO: escritor " + str(id) + " esta escrevendo quando ha outro escritor ou leitores!")
		self.escritores+=1

	def leitorSaindo(self,id):
		'''Recebe o id do leitor e registra que terminou a leitura.'''
		self.leitores-=1

	def escritorSaindo(self,id):
		'''Recebe o id do escritor e registra que terminou a leitura.'''
		self.escritores-=1

##sequencia de escritas e leituras
import verificaLE
le = verificaLE.LE()
le.leitorLendo(1)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorSaindo(1)
le.leitorBloqueado(1)
le.escritorEscrevendo(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(1)
le.escritorBloqueado(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorSaindo(1)
le.escritorEscrevendo(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.escritorBloqueado(2)
le.leitorBloqueado(1)
le.escritorSaindo(1)
le.leitorBloqueado(1)
le.escritorEscrevendo(2)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.escritorBloqueado(1)
le.leitorBloqueado(4)
le.leitorBloqueado(2)
le.leitorBloqueado(3)
le.escritorBloqueado(3)
le.leitorBloqueado(1)
le.escritorSaindo(2)
le.escritorEscrevendo(2)
le.leitorBloqueado(1)
le.escritorBloqueado(3)
le.leitorBloqueado(3)
le.leitorBloqueado(2)
le.leitorBloqueado(4)
le.escritorBloqueado(1)